### ISSUE TITLE
Can't import template

### ISSUE THREAD

**Issue by davidisko** [linuxsquad/zabbix_mdraid#5]
It says
    XML file contains fatal error 41:Specification mandate value for attribute data-pjax-transient [ Line: 32 | Column: 40 ]

zabbix 2.2.8-1+wheezy

**Comment by linuxsquad** [comment]
Can you post XML file that you trying to import? 

Did you see this forum post...

https://www.zabbix.com/forum/showthread.php?t=44758

**Comment by davidisko** [comment]
I'm trying to import zbx_export_templates.xml from this project to get mdadm monitoring in zabbix

**Comment by davidisko** [comment]
sorry my bad. i was uploading xml downloaded in html format. you can remove this issue.

**Comment by linuxsquad** [comment]
no problem
